---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-12.04-11
    driver:
      box: ubuntu-12.04
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: ubuntu-12.04-12
    driver:
      box: ubuntu-12.04
    provisioner:
      require_chef_omnibus: 12.20.3
  - name: ubuntu-14.04-11
    driver:
      box: ubuntu-14.04
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: ubuntu-14.04-12
    driver:
      box: ubuntu-14.04
    provisioner:
      require_chef_omnibus: 12.20.3
  - name: ubuntu-16.04-11
    driver:
      box: ubuntu-16.04
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: ubuntu-16.04-12
    driver:
      box: ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.20.3

suites:
  - name: default
    run_list:
      - recipe[lifecycle::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
